var movieTitle = "Amadeus";
movieTitle = "Arrival";
// movieTitle = 4;
movieTitle.toUpperCase();
var numCatLives = 9;
numCatLives++;
numCatLives = "zero";
var gameOver = false;
gameOver = true;
gameOver = "true";
